<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
df= pd.read_csv("/content/IMDB Dataset - IMDB Dataset.csv")

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

#Step-1 --> Lowercasing

In [8]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [9]:
# If i want to convert all movie review into lowercase then

df['review'] = df['review'].str.lower()

In [10]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

#Step-2--> Remove Html tags

In [11]:
import re #regular expression
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)

In [12]:
text= "<html><body><p> Movie1 </p><p> Actor - Aamir Khan </p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [13]:
remove_html_tags(text)

' Movie1  Actor - Aamir Khan  Click here to download'

In [14]:
# now we remove tags from IMBD datasets
df['review']=df['review'].apply(remove_html_tags)

In [15]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

#Step-3 --> Remove Url

In [16]:
# If i want to remove urls from text then

def remove_url(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [17]:
text2='For notebook click https://www.deture.com/delta/note1234acc'

In [18]:
remove_url(text2)

'For notebook click '

In [24]:
df['review']=df['review'].apply(remove_url)

#Step-4 --> Remove Punctuation

In [19]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [20]:
exclude=string.punctuation

In [21]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
  return text

In [22]:
text3= 'string. with. Punctuation?'

In [23]:
remove_punc(text3)

'string with Punctuation'

In [25]:
df['review']=df['review'].apply(remove_punc)

In [26]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

# Step-5--> Chatword Treatment

In [27]:
chat_words ={'u2': 'you too', 'BBL':'Be Back Later','GAL':'Get A Life'}

In [28]:
chat_words

{'u2': 'you too', 'BBL': 'Be Back Later', 'GAL': 'Get A Life'}

In [29]:
def chat_conversation(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [30]:
chat_conversation('BBL')

'Be Back Later'

# Step-6--> Spelling Correction

In [31]:
from textblob import TextBlob

In [32]:
incorrect_text = "ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner."

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

# Step-7 Removing Stepwords

In [33]:
import nltk # natural language tool kit
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [34]:
STOPWORDS = set(stopwords.words('english'))

In [36]:
#STOPWORDS

In [37]:
# manually work
def remove_stopwords(text):
  new_text =[]
  for word in text.split():
    if word in set(stopwords.words('english')):
      new_text.append('')
    else:
      new_text.append(word)
  x=new_text[:]
  new_text.clear()
  return " ".join(x)

In [38]:
remove_stopwords('probably my all-time favorite movie , a story of selflessness,sacrifice and dedication')

'probably  all-time favorite movie ,  story  selflessness,sacrifice  dedication'