<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/PCA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv('/content/Social_Network_Ads - Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df=df.drop(columns=['User ID','Gender'])

In [5]:
x=df.drop(columns=['Purchased'],axis=1)
y=df['Purchased']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,
                                               random_state=42)

In [7]:
pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('pca',PCA(n_components=2)),
    ('classifier',RandomForestClassifier(n_estimators=100,random_state=42))
])

In [8]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [9]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [10]:
y_pred=pipe.predict(x_test)

In [11]:
acc=accuracy_score(y_test,y_pred)
acc

0.8875

# on covid data

In [25]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [26]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
lb=LabelEncoder()

In [29]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [30]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [31]:
x=df.drop(columns=['has_covid'],axis=1)
y=df['has_covid']

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('pca',PCA(n_components=2)),
    ('classifier',RandomForestClassifier(n_estimators=100,random_state=42))
])

In [34]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [35]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [36]:
y_pred=pipe.predict(x_test)

In [37]:
acc=accuracy_score(y_test,y_pred)
acc

0.55

# for user behavior data

In [48]:
df=pd.read_csv('/content/userbehaviour - userbehaviour.csv')
df.head()

,userid,Average Screen Time,Average Spent on App (INR),Left Review,Ratings,New Password Request,Last Visited Minutes,Status
0,1001,17,634,1,9,7,2990,Installed
1,1002,0,54,0,4,8,24008,Uninstalled
2,1003,37,207,0,8,5,971,Installed
3,1004,32,445,1,6,2,799,Installed
4,1005,45,427,1,5,6,3668,Installed

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   userid                      999 non-null    int64
 1   Average Screen Time         999 non-null    int64
 2   Average Spent on App (INR)  999 non-null    int64
 3   Left Review                 999 non-null    int64
 4   Ratings                     999 non-null    int64
 5   New Password Request        999 non-null    int64
 6   Last Visited Minutes        999 non-null    int64
 7   Status                      999 non-null    object
dtypes: int64(7), object(1)
memory usage: 62.6+ KB

In [50]:
df.isnull().sum()

userid                        0
Average Screen Time           0
Average Spent on App (INR)    0
Left Review                   0
Ratings                       0
New Password Request          0
Last Visited Minutes          0
Status                        0
dtype: int64

In [51]:
from sklearn.preprocessing import LabelEncoder

In [52]:
lb=LabelEncoder()

In [53]:
df['Status']=lb.fit_transform(df['Status'])

In [54]:
x=df.drop(columns=['userid','Status'],axis=1)
y=df['Status']

In [55]:
# now we will use smote
from imblearn.over_sampling import SMOTE

In [56]:
smote=SMOTE()

In [57]:
x_res,y_res=smote.fit_resample(x,y)

In [58]:
x_res_train,x_res_test,y_res_train,y_res_test=train_test_split(x_res,y_res,test_size=0.2,random_state=42)

In [59]:
pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('pca',PCA(n_components=2)),
    ('classifier',RandomForestClassifier(n_estimators=100,random_state=42))
])

In [60]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [61]:
pipe.fit(x_res_train,y_res_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [62]:
y_pred=pipe.predict(x_res_test)

In [63]:
acc=accuracy_score(y_res_test,y_pred)
acc

0.9945504087193461